# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'HttpSwift' do

end

target 'HttpSwiftTests' do

end

target 'HttpSwiftUITests' do

end

source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '7.0'
pod 'AFNetworking', '~> 2.5'